### ISSUE TITLE
can_write not coming through

### ISSUE THREAD

**Issue by workingDog** [freetaxii/freetaxii-server#2]
I'm testing retrieving the collection with this:

`<!DOCTYPE html>
<html>
<head>
    <title>TAXII2</title>
    <meta charset="UTF-8">
</head>
<body>
<div id="demo"></div>
<script>
    function loadTaxii() {
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                document.getElementById("demo").innerHTML = this.responseText;
            }
        };
        xhttp.open("GET", "https://test.freetaxii.com:8000/api1/collections/9cfa669c-ee94-4ece-afd2-f8edac37d8fd/", true);
        xhttp.setRequestHeader('Accept', 'application/vnd.oasis.taxii+json');
        xhttp.setRequestHeader('Content-type', 'application/vnd.oasis.taxii+json');
        xhttp.send();
    };
    loadTaxii();
</script>
</body>
</html>`

I get:

`{"id":"9cfa669c-ee94-4ece-afd2-f8edac37d8fd","title":"Emerging Threats - Block Rules - Compromised IPs","description":"A collection of blocking rule indicators from Emerging Threats. Pulled live from: https://rules.emergingthreats.net/blockrules/emerging-botcc.excluded","can_read":true,"media_types":["application/vnd.oasis.stix+json"]}`

which does not contain the required can_write attribute.

**Comment by jordan2175** [comment]
This has now been fixed in libtaxii2.

**Comment by jordan2175** [comment]
I updated the code on the test server, so you should see it working now.

**Comment by workingDog** [comment]
great. Thanks again for your work.
