### ISSUE TITLE
Objects endpoint 

### ISSUE THREAD

**Issue by clenk** [freetaxii/freetaxii-server#3]
When testing the `/<api-root>/collections/<id>/objects/` endpoint, it seems that the server returns JSON if the Accept header is set to `application/vnd.oasis.taxii+json` but returns HTML if it is set to `application/vnd.oasis.stix+json`. Looking at [Section 5.3 in the spec](https://docs.google.com/document/d/1Jv9ICjUNZrOnwUXtenB1QcnBLO35RnjQcJLsa1mGSkI/pub#h.xlss9yvcfjov) it looks like it should accept the STIX media type.

**Comment by jordan2175** [comment]
Thanks for reporting this. I will get this fixed.

**Comment by jordan2175** [comment]
Fixed. The test server is running with the updated code.
