### ISSUE TITLE
Error when starting up freetaxii

### ISSUE THREAD

**Issue by ernsyn** [freetaxii/freetaxii-server#6]
Hi, 

Thanks for working on an implementation of taxii2 server. I'm trying to install and get freetaxii to run but I've been getting errors one after another. I've sort of managed to work through most of it but now stuck at another error.

This is my folder structure
`/Users/user/workspace/go/src/github.com/freetaxii/server/cmd/freetaxii`

This is a tree view
<img width="333" alt="screenshot 2018-12-16 at 10 54 17 pm" src="https://user-images.githubusercontent.com/6326517/50055142-9c88cd00-0185-11e9-99af-135b1dd1c13f.png">

And this is the error I'm getting now if I execute the freetaxii binary.
`2018/12/16 22:53:10 database execution error getting base index: %!(EXTRA sqlite3.Error=no such table: s_base_object)`

Any advise on how to solve this?

**Comment by jordan2175** [comment]
You need to run the following command to create the sqlite3 database and then move the file in to the freetaxii/db/ directory.

> /opt/go/src/github.com/freetaxii/server/cmd/createdb-> go run createSqlite3Database.go
